### PR TITLE
Replace tempdir with tempfile

### PR DESCRIPTION
**Pull request by jacob-hughes**
tempdir is deprecated and presents as a security vulnerability in cargo
audit.

### CODE REVIEW

**Comment by jacob-hughes** [comment]
I think this is failing because rustfmt doesn't work on the current version of nightly. I'll tweak the build script to `cargo fmt` conditionally.

**Comment by ltratt** [comment]
OK.

**Comment by jacob-hughes** [comment]
bors try

**Comment by jacob-hughes** [comment]
That seems to have done the trick

**Pull request merged**
