### PR TITLE
Add triple license

### PR DESCRIPTION
**Pull request by jacob-hughes**
And update the file headers to use the shorter format

### CODE REVIEW

**Comment by jacob-hughes** [comment]
I'll take your word for it. I'll do what `Vob` does because it means that the project shows up in the Github GUI as being licensed.

**Comment by jacob-hughes** [comment]
Fixed

**Comment by ltratt** [comment]
Please squash.

**Comment by jacob-hughes** [comment]
Squashed. I've updated the PR title too so hopefully your merge commit matches

**Pull request merged**
